AllCops:
  TargetRubyVersion: 2.3

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false